export const PLANTS: Record<string, any> = {
  sunflower: {
    id: "sunflower",
    name: "向日葵",
    emoji: "🌻",
    cost: 2,
    health: 100,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    ability: "generateSun",
    traits: ["photosynthesis"],
    description: "每3秒产生5阳光",
  },
  twin_sunflower: {
    id: "twin_sunflower",
    name: "双子葵",
    emoji: "🌼",
    cost: 4,
    health: 120,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    ability: "generateSun",
    traits: ["photosynthesis"],
    description: "每3秒产生10阳光",
  },
  marigold: {
    id: "marigold",
    name: "金盏花",
    emoji: "🏵️",
    cost: 3,
    health: 80,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    ability: "killReward",
    traits: ["photosynthesis"],
    description: "击杀+3阳光",
  },
  peashooter: {
    id: "peashooter",
    name: "豌豆射手",
    emoji: "🫛",
    cost: 1,
    health: 100,
    damage: 20,
    attackSpeed: 1500,
    attackRange: 8,
    traits: ["sharpshooter"],
    description: "基础DPS",
  },
  snow_pea: {
    id: "snow_pea",
    name: "寒冰射手",
    emoji: "❄️",
    cost: 2,
    health: 100,
    damage: 20,
    attackSpeed: 1500,
    attackRange: 8,
    ability: "slow",
    traits: ["sharpshooter", "frost"],
    description: "附带减速",
  },
  repeater: {
    id: "repeater",
    name: "双发射手",
    emoji: "🔫",
    cost: 3,
    health: 120,
    damage: 20,
    attackSpeed: 800,
    attackRange: 8,
    traits: ["sharpshooter"],
    description: "双重射击",
  },
  threepeater: {
    id: "threepeater",
    name: "三线射手",
    emoji: "🔫",
    cost: 4,
    health: 120,
    damage: 20,
    attackSpeed: 1500,
    attackRange: 8,
    ability: "tripleShot",
    traits: ["sharpshooter"],
    description: "攻击三行",
  },
  melonpult: {
    id: "melonpult",
    name: "西瓜投手",
    emoji: "🍉",
    cost: 5,
    health: 150,
    damage: 80,
    attackSpeed: 3000,
    attackRange: 8,
    ability: "splash",
    traits: ["sharpshooter"],
    description: "范围伤害",
  },
  cob_cannon: {
    id: "cob_cannon",
    name: "玉米加农炮",
    emoji: "🌽",
    cost: 6,
    health: 200,
    damage: 300,
    attackSpeed: 8000,
    attackRange: 10,
    ability: "splash",
    traits: ["sharpshooter"],
    description: "超慢超高伤",
  },
  wallnut: {
    id: "wallnut",
    name: "坚果墙",
    emoji: "🥜",
    cost: 2,
    health: 300,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    traits: ["defense"],
    description: "300血量",
  },
  tallnut: {
    id: "tallnut",
    name: "高坚果",
    emoji: "🌰",
    cost: 4,
    health: 500,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    traits: ["defense"],
    description: "500血量",
  },
  pumpkin: {
    id: "pumpkin",
    name: "南瓜头",
    emoji: "🎃",
    cost: 3,
    health: 250,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    ability: "armor",
    traits: ["defense"],
    description: "可套娃",
  },
  cherry_bomb: {
    id: "cherry_bomb",
    name: "樱桃炸弹",
    emoji: "🍒",
    cost: 3,
    health: 50,
    damage: 200,
    attackSpeed: 0,
    attackRange: 2,
    ability: "explodeOnDeath",
    traits: ["explosive"],
    description: "死亡爆炸",
  },
  jalapeno: {
    id: "jalapeno",
    name: "火爆辣椒",
    emoji: "🌶️",
    cost: 4,
    health: 50,
    damage: 300,
    attackSpeed: 0,
    attackRange: 8,
    ability: "explodeOnDeath",
    traits: ["explosive", "fire"],
    description: "整行伤害",
  },
  doomshroom: {
    id: "doomshroom",
    name: "毁灭菇",
    emoji: "🍄",
    cost: 6,
    health: 50,
    damage: 500,
    attackSpeed: 0,
    attackRange: 5,
    ability: "explodeOnDeath",
    traits: ["explosive"],
    description: "大范围清场",
  },
  torchwood: {
    id: "torchwood",
    name: "火炬树桩",
    emoji: "🔥",
    cost: 3,
    health: 150,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    ability: "damageBuff",
    traits: ["fire", "support"],
    description: "增伤光环",
  },
  magnetshroom: {
    id: "magnetshroom",
    name: "磁力菇",
    emoji: "🧲",
    cost: 3,
    health: 100,
    damage: 0,
    attackSpeed: 5000,
    attackRange: 5,
    ability: "stealArmor",
    traits: ["support"],
    description: "吸防具",
  },
  cactus: {
    id: "cactus",
    name: "仙人掌",
    emoji: "🌵",
    cost: 3,
    health: 120,
    damage: 30,
    attackSpeed: 1500,
    attackRange: 8,
    ability: "pierce",
    traits: ["sharpshooter"],
    description: "穿透攻击",
  },
};

export const ZOMBIES: Record<string, any> = {
  normal: {
    id: "normal",
    name: "普通僵尸",
    emoji: "🧟",
    health: 80,
    speed: 0.5,
    damage: 10,
    reward: 5,
    description: "基础单位",
  },
  cone: {
    id: "cone",
    name: "路障僵尸",
    emoji: "🚧",
    health: 160,
    speed: 0.5,
    damage: 10,
    reward: 8,
    description: "2倍血量",
  },
  bucket: {
    id: "bucket",
    name: "铁桶僵尸",
    emoji: "🪣",
    health: 240,
    speed: 0.5,
    damage: 10,
    reward: 10,
    description: "3倍血量",
  },
  runner: {
    id: "runner",
    name: "跑酷僵尸",
    emoji: "🏃",
    health: 60,
    speed: 1.0,
    damage: 10,
    reward: 8,
    description: "速度快",
  },
  pole_vaulter: {
    id: "pole_vaulter",
    name: "撑杆跳僵尸",
    emoji: "🦘",
    health: 120,
    speed: 0.8,
    damage: 15,
    reward: 12,
    ability: "jump",
    description: "跳过植物",
  },
  catapult: {
    id: "catapult",
    name: "投石车僵尸",
    emoji: "🚗",
    health: 150,
    speed: 0.4,
    damage: 20,
    reward: 15,
    ability: "ranged",
    description: "远程攻击",
  },
  gargantuar: {
    id: "gargantuar",
    name: "巨人僵尸",
    emoji: "👹",
    health: 600,
    speed: 0.3,
    damage: 50,
    reward: 30,
    ability: "smash",
    description: "Boss级",
  },
  zomboss: {
    id: "zomboss",
    name: "僵王博士",
    emoji: "🤖",
    health: 2000,
    speed: 0.1,
    damage: 100,
    reward: 100,
    ability: "boss",
    description: "最终Boss",
  },
};
