import { PlantConfig, ZombieConfig, TraitConfig } from '../types/index'

export const PLANTS: Record<string, PlantConfig> = {
  sunflower: {
    id: 'sunflower',
    name: '向日葵',
    emoji: '🌻',
    cost: 2,
    health: 80,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    ability: 'generateSun',
    traits: ['SUN'],
    description: '每3秒产生5点阳光',
  },
  twin_sunflower: {
    id: 'twin_sunflower',
    name: '双子葵',
    emoji: '🌻🌻',
    cost: 4,
    health: 100,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    ability: 'generateSun',
    traits: ['SUN'],
    description: '每3秒产生10点阳光',
  },
  marigold: {
    id: 'marigold',
    name: '金盏花',
    emoji: '🌼',
    cost: 3,
    health: 90,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    ability: 'bonusGold',
    traits: ['SUN'],
    description: '击杀僵尸额外获得3点阳光',
  },
  peashooter: {
    id: 'peashooter',
    name: '豌豆射手',
    emoji: '🫛',
    cost: 1,
    health: 100,
    damage: 15,
    attackSpeed: 1500,
    attackRange: 5,
    projectile: 'pea',
    traits: ['PEASHOOTER'],
    description: '发射豌豆攻击僵尸',
  },
  snow_pea: {
    id: 'snow_pea',
    name: '寒冰射手',
    emoji: '❄️',
    cost: 2,
    health: 100,
    damage: 12,
    attackSpeed: 1500,
    attackRange: 5,
    projectile: 'snow',
    effect: 'slow',
    traits: ['PEASHOOTER', 'ICE'],
    description: '发射寒冰豌豆，减缓僵尸',
  },
  repeater: {
    id: 'repeater',
    name: '双发射手',
    emoji: '🫛🫛',
    cost: 3,
    health: 120,
    damage: 15,
    attackSpeed: 1500,
    attackRange: 5,
    projectile: 'pea',
    traits: ['PEASHOOTER'],
    description: '一次发射两颗豌豆',
  },
  threepeater: {
    id: 'threepeater',
    name: '三线射手',
    emoji: '🫛🫛🫛',
    cost: 4,
    health: 140,
    damage: 15,
    attackSpeed: 1400,
    attackRange: 5,
    projectile: 'pea',
    traits: ['PEASHOOTER'],
    description: '同时攻击三行僵尸',
  },
  melon_pult: {
    id: 'melon_pult',
    name: '西瓜投手',
    emoji: '🍉',
    cost: 5,
    health: 150,
    damage: 40,
    attackSpeed: 2500,
    attackRange: 4,
    projectile: 'melon',
    effect: 'splash',
    traits: ['PEASHOOTER', 'EXPLOSIVE'],
    description: '发射西瓜造成范围伤害',
  },
  cob_cannon: {
    id: 'cob_cannon',
    name: '玉米加农炮',
    emoji: '🌽',
    cost: 6,
    health: 200,
    damage: 100,
    attackSpeed: 6000,
    attackRange: 8,
    projectile: 'corn',
    traits: ['PEASHOOTER', 'EXPLOSIVE'],
    description: '超慢但超高伤害，全屏攻击',
  },
  wall_nut: {
    id: 'wall_nut',
    name: '坚果墙',
    emoji: '🥜',
    cost: 2,
    health: 300,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    traits: ['DEFENSE'],
    description: '高生命值的防御植物',
  },
  tall_nut: {
    id: 'tall_nut',
    name: '高坚果',
    emoji: '🌰',
    cost: 4,
    health: 500,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    traits: ['DEFENSE'],
    description: '超高生命，阻挡飞行',
  },
  pumpkin: {
    id: 'pumpkin',
    name: '南瓜头',
    emoji: '🎃',
    cost: 3,
    health: 250,
    damage: 0,
    attackSpeed: 0,
    attackRange: 0,
    traits: ['DEFENSE'],
    description: '可套在其他植物上提供护甲',
  },
  cherry_bomb: {
    id: 'cherry_bomb',
    name: '樱桃炸弹',
    emoji: '🍒',
    cost: 3,
    health: 50,
    damage: 0,
    attackSpeed: 0,
    attackRange: 1,
    ability: 'explodeOnDeath',
    traits: ['EXPLOSIVE'],
    description: '死亡时对周围造成200伤害',
  },
  jalapeno: {
    id: 'jalapeno',
    name: '火爆辣椒',
    emoji: '🌶️',
    cost: 4,
    health: 80,
    damage: 0,
    attackSpeed: 0,
    attackRange: 8,
    ability: 'laneDamage',
    traits: ['EXPLOSIVE', 'FIRE'],
    description: '对整行造成150伤害',
  },
  doom_shroom: {
    id: 'doom_shroom',
    name: '毁灭菇',
    emoji: '🍄',
    cost: 6,
    health: 100,
    damage: 0,
    attackSpeed: 0,
    attackRange: 3,
    ability: 'megaExplode',
    traits: ['EXPLOSIVE'],
    description: '大范围500伤害，留下坑洞',
  },
  torchwood: {
    id: 'torchwood',
    name: '火炬树桩',
    emoji: '🔥',
    cost: 3,
    health: 150,
    damage: 10,
    attackSpeed: 0,
    attackRange: 0,
    ability: 'damageAura',
    traits: ['FIRE'],
    description: '同行射手伤害+50%',
  },
  magnet_shroom: {
    id: 'magnet_shroom',
    name: '磁力菇',
    emoji: '🧲',
    cost: 3,
    health: 120,
    damage: 0,
    attackSpeed: 3000,
    attackRange: 3,
    ability: 'stealArmor',
    traits: ['SUPPORT'],
    description: '移除僵尸的防具',
  },
  cactus: {
    id: 'cactus',
    name: '仙人掌',
    emoji: '🌵',
    cost: 3,
    health: 120,
    damage: 20,
    attackSpeed: 1800,
    attackRange: 6,
    projectile: 'spike',
    traits: ['PEASHOOTER'],
    description: '发射穿透尖刺',
  },
  squash: {
    id: 'squash',
    name: '倭瓜',
    emoji: '🎃',
    cost: 3,
    health: 100,
    damage: 150,
    attackSpeed: 0,
    attackRange: 2,
    ability: 'smash',
    traits: ['EXPLOSIVE'],
    description: '砸扁相邻的僵尸',
  },
}

export const ZOMBIES: Record<string, ZombieConfig> = {
  normal: {
    id: 'normal',
    name: '普通僵尸',
    emoji: '🧟',
    health: 80,
    damage: 10,
    speed: 0.3,
    reward: 5,
  },
  cone: {
    id: 'cone',
    name: '路障僵尸',
    emoji: '🚧',
    health: 160,
    damage: 10,
    speed: 0.25,
    reward: 8,
  },
  bucket: {
    id: 'bucket',
    name: '铁桶僵尸',
    emoji: '🪣',
    health: 240,
    damage: 12,
    speed: 0.2,
    reward: 12,
  },
  pole_vault: {
    id: 'pole_vault',
    name: '撑杆跳僵尸',
    emoji: '🏃',
    health: 120,
    damage: 15,
    speed: 0.5,
    reward: 10,
    special: 'jump',
  },
  fast: {
    id: 'fast',
    name: '跑酷僵尸',
    emoji: '💨',
    health: 60,
    damage: 8,
    speed: 0.6,
    reward: 6,
  },
  catapult: {
    id: 'catapult',
    name: '投石车僵尸',
    emoji: '🚗',
    health: 150,
    damage: 20,
    speed: 0.15,
    reward: 15,
    special: 'ranged',
  },
  gargantuar: {
    id: 'gargantuar',
    name: '巨人僵尸',
    emoji: '👹',
    health: 600,
    damage: 50,
    speed: 0.12,
    reward: 30,
  },
  zomboss: {
    id: 'zomboss',
    name: '僵王博士',
    emoji: '🤖',
    health: 2000,
    damage: 100,
    speed: 0,
    reward: 100,
    special: 'boss',
  },
}

export const TRAITS: Record<string, TraitConfig> = {
  SUN: {
    id: 'SUN',
    name: '光合作用',
    description: '每回合额外获得阳光',
    thresholds: [2, 4],
    effects: [
      { type: 'sun_per_turn', value: 3 },
      { type: 'sun_per_turn', value: 8 },
    ],
  },
  PEASHOOTER: {
    id: 'PEASHOOTER',
    name: '神射手',
    description: '射手系植物攻击速度提升',
    thresholds: [2, 3, 5],
    effects: [
      { type: 'attack_speed', value: 0.15 },
      { type: 'attack_speed', value: 0.35 },
      { type: 'attack_speed', value: 0.6 },
    ],
  },
  DEFENSE: {
    id: 'DEFENSE',
    name: '铜墙铁壁',
    description: '防御系植物生命值提升',
    thresholds: [2, 3, 4],
    effects: [
      { type: 'health', value: 0.2 },
      { type: 'health', value: 0.4 },
      { type: 'health', value: 0.6 },
    ],
  },
  EXPLOSIVE: {
    id: 'EXPLOSIVE',
    name: '爆裂火花',
    description: '爆炸伤害提升',
    thresholds: [2, 3],
    effects: [
      { type: 'explosion_damage', value: 0.25 },
      { type: 'explosion_damage', value: 0.5 },
    ],
  },
  ICE: {
    id: 'ICE',
    name: '寒冰之心',
    description: '攻击概率冻结敌人',
    thresholds: [2],
    effects: [
      { type: 'freeze_chance', value: 0.2 },
    ],
  },
  FIRE: {
    id: 'FIRE',
    name: '熊熊烈火',
    description: '火焰伤害提升，附带点燃效果',
    thresholds: [2, 3],
    effects: [
      { type: 'fire_damage', value: 0.2 },
      { type: 'fire_damage', value: 0.4 },
    ],
  },
  SUPPORT: {
    id: 'SUPPORT',
    name: '后勤保障',
    description: '辅助植物效果增强',
    thresholds: [2],
    effects: [
      { type: 'support_effect', value: 0.5 },
    ],
  },
}