export { PLANTS, ZOMBIES, TRAITS } from './game.config'
export { GAME_CONFIG } from './constants'
export { WAVES } from './waves.config'
export { ITEMS, getDropRarity, getRandomItem, getRarityColor } from './items.config'
export type { ItemConfig, ItemEffect } from './items.config'